Fix base64 declaration and remove unused cdefs.
> fatal error: 'sys/cdefs.h' file not found

Delete cdefs include, because it's an internal header of some libc
implementations, not containing anything still used in fdm.

> error: a parameter list without types is only allowed in a function
definition

Specify types where parameter names were, probably by mistake.